on:
  workflow_dispatch:

jobs:
  dev:
    name: run test in dev
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: sleep 45
      - run: echo 'hello dev'

  prod:
    needs: dev
    name: run test in prod
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello prod'
      - name: Check approver
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "who approved?"
          APPROVER=$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/approvals --jq '.[0].user.login')
          echo "Approved for production by $APPROVER"
